# Generated by Django 5.0.2 on 2024-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drone_images'),
        ),
    ]
