# Generated by Django 5.0.2 on 2024-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='category',
            field=models.CharField(choices=[('armed', 'Armed'), ('unarmed', 'Unarmed')], max_length=100),
        ),
    ]
